{% set name = "aws-cdk.aws-acmpca" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.aws-acmpca-{{ version }}.tar.gz
  sha256: 7221302ca5603c9e0397999187d7ff82c07da17c5d6a8768a29b09153f83bd54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - aws-cdk.core ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.aws_acmpca
    - aws_cdk.aws_acmpca._jsii
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/aws-cdk
  summary: The CDK Construct Library for AWS::ACMPCA
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
